### ISSUE TITLE
get a video from api

### ISSUE THREAD

**Issue by MattManson** [MattManson/space_flix#11]
just get one video, be able to display it on a page

**Comment by aconstantinou123** [comment]
https://images-assets.nasa.gov/video/JPL-19790709-VOYAGEf-0001-AVC2002151%20Voyager%202%20at%20Jupiter/collection.json

**Comment by aconstantinou123** [comment]
https://images.nasa.gov/docs/images.nasa.gov_api_docs.pdf

**Comment by aconstantinou123** [comment]
https://images-api.nasa.gov/search?media_type=video&keywords=jupiter
